spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authapp
    username: root
    password: 9078
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
